// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFYIBlS7qQdp1v4AYIov4FD3mXGFd_ciY',
    appId: '1:822886936867:web:eeb5baf9246fc4bda05c96',
    messagingSenderId: '822886936867',
    projectId: 'testdeliveryapp-14fb9',
    authDomain: 'testdeliveryapp-14fb9.firebaseapp.com',
    storageBucket: 'testdeliveryapp-14fb9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXVNAEmJOKYMfB15AsbJlmh4utApxxEZg',
    appId: '1:822886936867:android:b076a83c392d2041a05c96',
    messagingSenderId: '822886936867',
    projectId: 'testdeliveryapp-14fb9',
    storageBucket: 'testdeliveryapp-14fb9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDSmWCp-VGp2XEDQXrPouVP0aHaeiwfyM',
    appId: '1:822886936867:ios:e4ce50c5b1d946a9a05c96',
    messagingSenderId: '822886936867',
    projectId: 'testdeliveryapp-14fb9',
    storageBucket: 'testdeliveryapp-14fb9.appspot.com',
    iosClientId: '822886936867-rlgl6dufvvoojcliclmnh88l2ccanhd0.apps.googleusercontent.com',
    iosBundleId: 'com.example.deliveryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDSmWCp-VGp2XEDQXrPouVP0aHaeiwfyM',
    appId: '1:822886936867:ios:ec6ebcdeaef7155ba05c96',
    messagingSenderId: '822886936867',
    projectId: 'testdeliveryapp-14fb9',
    storageBucket: 'testdeliveryapp-14fb9.appspot.com',
    iosClientId: '822886936867-jndn331g57b8k1usr7251d0jm33kj5pd.apps.googleusercontent.com',
    iosBundleId: 'com.example.deliveryApp.RunnerTests',
  );
}
